version: "3.9"
name: project_name
services:
    # app:
    #     build: .
    #     ports:
    #         - "${APP_PORT}:${APP_PORT}"
    #     depends_on:
    #         postgres:
    #             condition: service_healthy

    #     environment:
    #         - DB_HOST=postgres

    postgres:
        image: postgres
        ports:
            - "${DB_PORT}:5432"
        environment:
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_NAME}"

        volumes:
            - project_name:/var/lib/postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $${DB_NAME} -U $${DB_}"]
            interval: 30s
            timeout: 60s
            retries: 5
            start_period: 80s
        restart: on-failure

volumes:
    project_name:
